notes/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'notes'
urlpatterns = [
    url(r'^$', views.Home, name='home'),
    url(r'^cadastra/$', views.Cadastra, name='cadastra'),
    url(r'^lista/$', views.Lista, name='lista'),
    url(r'^note/(?P<pk>\d+)/edita/$', views.Edita, name='edita'),
    url(r'^note/(?P<pk>\d+)/detalhe/$', views.Detalhe, name='detalhe'),
    url(r'^note/(?P<pk>\d+)/delete/$', views.Delete, name='delete'),        
    url(r'^login/$', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),        
    url(r'^logout/$', auth_views.logout, {'template_name': 'accounts/logout.html'}, name='logout'), 
    url(r'^profile/$', views.Profile , name='profile'),
    url(r'^profile/edit/$', views.Edit_profile , name='edit_profile'),
    url(r'^register/$', views.Register , name='register'),
    url(r'^change-password/$', views.Change_Password , name='change-password'),
    url(r'^responsavel/$', views.Add_Responsavel , name='add-responsavel'),
    url(r'^responsavel/(?P<pk>\d+)/Edit$', views.Edit_Responsavel , name='edit-responsavel'),
    url(r'^responsavel/(?P<pk>\d+)/Detalhe$', views.Detalhe_Responsavel , name='detalhe-responsavel'),
    url(r'^responsavel/(?P<pk>\d+)/Delete$', views.Delete_Responsavel , name='delete-responsavel'),
    url(r'^responsavel/lista$', views.Lista_Responsavel , name='lista-responsavel'),
    url(r'^user/lista$', views.User_List , name='user-list'),

]

project01/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^notes/', include('notes.urls')),
    url(r'^admin/', admin.site.urls),
]

notes/models.py
from django.db import models
from datetime import datetime

class Note(models.Model):
    responsavel = models.CharField(max_length=80)
    descricao = models.CharField(max_length=800)
    data = models.DateField('Data')    
    def __str__(self):
        return self.descricao

class Responsavel(models.Model):
    responsavel = models.CharField('Codigo', max_length=80)
    descricao = models.CharField('Nome Completo', max_length=800)
    data_registro = models.DateField('Date', null=True)    
    def __str__(self):
        return self.responsavel

notes/forms.py
from django import forms
from .models import Note, Responsavel
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError

class NoteForm(forms.ModelForm):	
	descricao = forms.CharField(widget=forms.Textarea)
	class Meta:
		model = Note
		fields = (
		'responsavel',
		'descricao',		
		)

	def clean_responsavel(self):
		responsavel = self.cleaned_data['responsavel']
		if Responsavel.objects.filter(responsavel=responsavel).exists() == False:
			raise ValidationError("Responsavel não cadastrado")			
		return responsavel

class NoteFormView(forms.ModelForm):	
	responsavel = forms.CharField(disabled=True)
	descricao = forms.CharField(widget=forms.Textarea, disabled=True)	
	data = forms.DateField(disabled=True)
	class Meta:
		model = Note
		fields = (
		'responsavel',
		'descricao',
		'data',
		)

class ResponsavelForm(forms.ModelForm):	
	class Meta:
		model = Responsavel		
		fields = (
		'responsavel',
		'descricao'
		)

	def clean_responsavel(self):
		responsavel = self.cleaned_data['responsavel']
		if Responsavel.objects.filter(responsavel=responsavel).exists():
			raise ValidationError("Responsavel já cadastrado")			
		return responsavel

class ResponsavelFormEdit(forms.ModelForm):	
	responsavel = forms.CharField(disabled=True)
	class Meta:
		model = Responsavel		
		fields = (
		'responsavel',
		'descricao'
		)	

class EditProfileForm(UserChangeForm):
	class Meta:
		model = User
		fields = (
		'email',
		'first_name',
		'last_name',
		'password'
		)


class RegisterProfileForm(UserCreationForm):
	email = forms.EmailField(required=True)
	
	class Meta:
		model = User
		fields = (
		'username',
		'email',
		'first_name',
		'last_name',
		'password1',
		'password2'
		)		

	def save(self, commit=True):
		user = super(RegisterProfileForm, self).save(commit=False)
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.email = self.cleaned_data['email']

		if commit:
			user.save()

notes/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import (
    authenticate,
    login,
    update_session_auth_hash
    )
from django.contrib.auth.forms import (
    UserChangeForm, 
    UserCreationForm, 
    PasswordChangeForm
    )

from .models import Note, Responsavel
from .forms import (
    NoteForm,
    NoteFormView,
    EditProfileForm,
    RegisterProfileForm,
    ResponsavelForm,
    ResponsavelFormEdit
    )

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


#@login_required(login_url='notes:login')
def Lista(request):
    latest_question_list = Note.objects.order_by('data')
    context = {'testeq': latest_question_list}
    return render(request, 'notes/lista.html', context)

def Home(request):
	return render(request, 'notes/home.html', {})

def Cadastra(request):
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            anotacao = form.save(commit=False)            
            anotacao.data = timezone.now()
            anotacao.save()            
            return redirect('notes:lista')
    else:
        form = NoteForm()

    return render(request, 'notes/edita.html', {'form': form})

def Edita(request, pk):	
	NoteEdit = get_object_or_404(Note, pk=pk)
	if request.method == 'POST':
		form = NoteForm(request.POST, instance=NoteEdit)

		if form.is_valid():
			form.save()
			return redirect('notes:detalhe', pk=pk)

	else:
		form = NoteForm(instance=NoteEdit)

	return render(request, 'notes/edita.html', {'form': form, 'notes': NoteEdit})

def Detalhe(request, pk):
    NoteDetail = get_object_or_404(Note, pk=pk)
    form = NoteFormView(instance=NoteDetail)
    args = {'form': form, 'notes': NoteDetail}    
    return render(request, 'notes/detalhe.html', args)

def Delete(request, pk):
    note = get_object_or_404(Note, pk=pk)    
    form = NoteFormView(instance=note)

    if request.method=='POST':
        note.delete()
        return redirect('notes:lista')


    return render(request, 'notes/delete.html', {'form': form, 'notes':note})

def Profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)

def Edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('notes:profile')

    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)

def Register(request):
    if request.method == 'POST':
        form = RegisterProfileForm(request.POST)
        if form.is_valid():
            form.save()

            username = request.POST['username']
            password = request.POST['password1']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('notes:profile')            
                
        args = {'form': form}
        return render(request,'accounts/register.html', args)
        
    else:
        form = RegisterProfileForm()
        args = {'form': form}
        return render(request,'accounts/register.html', args)

def Change_Password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('notes:profile')
        else:
            args = {'form': form}
            return render(request,'accounts/change_password.html', args)


    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

def Add_Responsavel(request):
    if request.method == 'POST':
        form = ResponsavelForm(request.POST)
        if form.is_valid():
            responsavel = form.save(commit=False)            
            responsavel.data_registro = timezone.now()
            responsavel.save()
            return redirect('notes:lista-responsavel')

    else:
        form = ResponsavelForm()

    return render(request, 'notes/responsavel.html', {'form': form})

def Edit_Responsavel(request, pk): 
    ResponsavelEdit = get_object_or_404(Responsavel, pk=pk)
    if request.method == 'POST':
        form = ResponsavelFormEdit(request.POST, instance=ResponsavelEdit)

        if form.is_valid():
            form.save()
            return redirect('notes:detalhe-responsavel', pk=pk)

    else:
        form = ResponsavelFormEdit(instance=ResponsavelEdit)

    return render(request, 'notes/responsavel.html', {'form': form})

def Detalhe_Responsavel(request, pk):        
    ResponsavelDetail = get_object_or_404(Responsavel, pk=pk)
    return render(request, 'notes/detalhe_responsavel.html',
         {'responsavel': ResponsavelDetail})

def Lista_Responsavel(request):
    latest_question_list = Responsavel.objects.order_by('responsavel')
    context = {'lista_resp': latest_question_list}
    return render(request, 'notes/lista_responsavel.html', context)

def Delete_Responsavel(request, pk):
    responsavel = get_object_or_404(Responsavel, pk=pk)    
    if request.method=='POST':
        responsavel.delete()
        return redirect('notes:lista-responsavel')


    return render(request, 'notes/delete_responsavel.html', {'responsavel':responsavel})



def User_List(request):
    user_list = User.objects.all()
    page = request.GET.get('page', 1)

    paginator = Paginator(user_list, 10)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    return render(request, 'notes/user_list.html', { 'users': users })

notes/templates/notes/base.html
<!DOCTYPE html>
<html>
<head>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  {% block title %}
    <title>Título</title>
  {% endblock title %}

  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'notes/bootstrap.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'notes/style.css' %}" />        
  <script type="text/javascript" src="{% static 'notes/jquery.js' %}"></script>        
  <script type="text/javascript" src="{% static 'notes/jquery.mask.js' %}"></script>
</head>
<body>        
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'notes:home' %}">Home</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Anotações <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'notes:cadastra' %}">Cadastra</a></li>
                <li><a href="{% url 'notes:lista' %}">Lista</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Responsavel <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'notes:add-responsavel' %}">Cadastra</a></li>
                <li><a href="{% url 'notes:lista-responsavel' %}">Consulta/Edita</a></li>
                
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="{% url 'notes:user-list' %}">Lista User</a>              
            </li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated == False %}
            <li><a href="{% url 'notes:login' %}">Login</a></li>            
            <li><a href="{% url 'notes:register' %}">Register</a></li>            
            {% else %} 
            <li><a href="{% url 'notes:profile' %}">{{ user.get_username }}</a></li>            
            <li><a class="" href="{% url 'notes:logout' %}">Logout</a> </li>            

            {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
        
    <div class="container-fluid">
    {% block content %}

    {% endblock content %}
    </div>
    </div>
    <script type="text/javascript" src="{% static 'notes/bootstrap.js' %}"></script>
</body>
</html>

notes/templates/notes/delete.html
{% extends 'notes/base.html' %}

{% block content %}
        
<h1>Detalhes</h1>
<form method="post">{% csrf_token %}
	<div class="divdeleta">
		<h4>Are you sure you want to delete ?</h4>
		<button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-ok"></span> </button>
	    <a class="btn btn-default" href="{% url 'notes:detalhe' pk=notes.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
	    <p>
    </div
		<br>
		<table class="table table-hover alinhamento">
			{{ form.as_table }}
		</table>
    
</form>


{% endblock content %}

notes/templates/notes/delete_responsavel.html
{% extends 'notes/base.html' %}

{% block content %}
        
<form method="post">{% csrf_token %}
	<div class="divdeleta">
		<h4>Are you sure you want to delete "{{ responsavel.responsavel }}" ?</h4>
		<p>
		<button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-ok"></span> </button>
    	<a class="btn btn-default" href="{% url 'notes:detalhe-responsavel' pk=responsavel.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
	</div>
	<h1>Detalhes</h1>
    {{ responsavel.responsavel }}<br>
    {{ responsavel.descricao }}<br>
    {{ responsavel.data_registro }}<br><br><br>
    
</form>

{% endblock content %}

notes/templates/notes/detalhe.html
{% extends 'notes/base.html' %}

{% block content %}
        
    <h1>Detalhes</h1>
    <table class="table table-hover alinhamento">
		{{ form.as_table }}
	</table>	

	<a class="btn btn-default" href="{% url 'notes:edita' pk=notes.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
	<a class="btn btn-default" href="{% url 'notes:delete' pk=notes.pk %}"><span class="glyphicon glyphicon-trash"></span></a>

{% endblock content %}

notes/templates/notes/detalhe_responsavel.html
{% extends 'notes/base.html' %}

{% block content %}
        
    <h1>Detalhes</h1>
    {{ responsavel.responsavel }}<br>
    {{ responsavel.descricao }}<br>
    {{ responsavel.data_registro }}<br><br><br>

    
    {{ teste2.descricao }}
    


	<a class="btn btn-default" href="{% url 'notes:edit-responsavel' pk=responsavel.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
	<a class="btn btn-default" href="{% url 'notes:delete-responsavel' pk=responsavel.pk %}"><span class="glyphicon glyphicon-trash"></span></a>

{% endblock content %}

notes/templates/notes/edit_responsavel.html
{% extends 'notes/base.html' %}

{% block content %}
        
    <h1>Responsavel</h1>
    <form method="POST" class="tabela-lista">{% csrf_token %}
    	<table class="table table-hover alinhamento">
    		{{ form.as_table }}
    	</table>
        <button type="submit" class="save btn btn-default"><span class="glyphicon glyphicon-ok"></span></button>        
        <a class="btn btn-default" href="{% url 'notes:lista-responsavel' %}"><span class="glyphicon glyphicon-remove"></span></a>
    </form>	       

{% endblock content %}

notes/templates/notes/edita.html
{% extends 'notes/base.html' %}

{% block content %}
        
    <h1>Anotação</h1>
    <form method="POST" class="tabela-lista">{% csrf_token %}
    	<table class="table table-hover alinhamento">
    		{{ form.as_table }}
    	</table>
        <button type="submit" class="save btn btn-default"><span class="glyphicon glyphicon-ok"></span></button>
        {% if notes.pk != None %}        
            <a class="btn btn-default" href="{% url 'notes:detalhe' pk=notes.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
        {% else %}        
            <a class="btn btn-default" href="{% url 'notes:lista' %}"><span class="glyphicon glyphicon-remove"></span></a>
        {% endif %}
    </form>	   

    <script>
		$(document).ready(function () { 
	        var $seuCampoData = $("#id_data");
	        $seuCampoData.mask("9999-99-99");
	    });

	</script>

{% endblock content %}

notes/templates/notes/home.html
{% extends 'notes/base.html' %}

{% block title %}
	<title>Home</title>
{% endblock title %}



{% block content %}

<h1> Ola mundo </h1>

{% endblock content %}

notes/templates/notes/lista.html
{% extends 'notes/base.html' %}

{% block content %}        

	<table class="table table-hover tabela-lista">
		<tr><th>Responsavel </th><th>Descricao </th><th>Data</th></tr>
		{% for notes in testeq %}
			<tr><td>{{ notes.responsavel }}</td><td>{{ notes.descricao }}</td><td>{{ notes.data }}</td><td> <a class="btn btn-default" href="{% url 'notes:detalhe' pk=notes.pk %}"><span class="glyphicon glyphicon-list-alt"></span></a></td></tr>
	        
	    {% endfor %}
	</table>	

{% endblock content %}

notes/templates/notes/lista_responsavel.html
{% extends 'notes/base.html' %}

{% block content %}        

	<table class="table table-hover tabela-lista">
		<tr><th>Codigo </th><th>Nome Completo </th><th>Data Registro</th></tr>
		{% for responsavel in lista_resp %}
			<tr><td>{{ responsavel.responsavel }}</td><td>{{ responsavel.descricao }}</td><td>{{ responsavel.data_registro }}</td><td> <a class="btn btn-default" href="{% url 'notes:detalhe-responsavel' pk=responsavel.pk %}"><span class="glyphicon glyphicon-list-alt"></span></a></td></tr>
	        
	    {% endfor %}
	</table>	

{% endblock content %}

notes/templates/notes/responsavel.html
{% extends 'notes/base.html' %}

{% block content %}
        
    <h1>Responsavel</h1>
    <form method="POST" class="tabela-lista">{% csrf_token %}
    	<table class="table table-hover alinhamento">
    		{{ form.as_table }}
    	</table>
        <button type="submit" class="save btn btn-default"><span class="glyphicon glyphicon-ok"></span></button>        
        <a class="btn btn-default" href="{% url 'notes:home' %}"><span class="glyphicon glyphicon-remove"></span></a>
    </form>	       

{% endblock content %}

notes/templates/notes/user_list.html
<!DOCTYPE html>
<html>
<head>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  {% block title %}
    <title>Título</title>
  {% endblock title %}

  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'notes/bootstrap.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'notes/style.css' %}" />        
  <script type="text/javascript" src="{% static 'notes/jquery.js' %}"></script>        
  <script type="text/javascript" src="{% static 'notes/jquery.mask.js' %}"></script>
</head>
<body>     
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Username</th>
        <th>First name</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      {% for users in users %}
        <tr>
          <td>{{ users.username }}</td>
          <td>{{ users.first_name }}</td>
          <td>{{ users.email }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% if users.has_other_pages %}
  <ul class="pagination">
    {% if users.has_previous %}
      <li><a href="?page={{ users.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in users.paginator.page_range %}
      {% if users.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if users.has_next %}
      <li><a href="?page={{ users.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
<br><br>

{% if users.has_other_pages %}
  <ul class="pagination">
  {% if users.has_previous %}
    <li><a href="?page=1"><<</a></li>
    <li><a href="?page={{ users.previous_page_number }}"><</a></li>
  {% else %}
      <li class="disabled"><span class=""><<</span></li>
      <li class="disabled"><span><</span></li>
  {% endif %}
    {% for page in users.paginator.page_range %}
    {% if page >= users.number|add:"-3" and page < users.number %}
      <li><a href="?page={{ page }}">{{ page }}</a></li>
    {% endif %}
    {% ifequal users.number page %}
      <li class="active"><span>{{ users.number }}</span></li>
    {% endifequal %}
    {% if page <= users.number|add:"3" and page > users.number %}
      <li><a href="?page={{ page }}">{{ page }}</a></li>
    {% endif %}
    {% endfor %}
  {% if users.has_next %}
      <li><a href="?page={{ users.next_page_number }}"><span class="">></span></a></li>
      <li><a href="?page={{ users.paginator.num_pages }}"><span class="">>></span></a></li>
    {% else %}
      <li class="disabled"><span class="">></span></li>      
      <li class="disabled"><span class="">>></span></li>
    {% endif %}
    
  </ul>
{% endif %}


</body>
</html>